// <auto-generated />
using System;
using GrandLux.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrandLux.Migrations
{
    [DbContext(typeof(GrandLuxDBContext))]
    partial class GrandLuxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrandLux.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnName("E_Mail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("First_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnName("Job_Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("Last_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("EMail")
                        .IsUnique()
                        .HasName("IX_Employees")
                        .HasFilter("[E_Mail] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasName("IX_Employees_1");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GrandLux.Models.Guests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnName("E_Mail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("First_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("Last_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("EMail")
                        .IsUnique()
                        .HasName("IX_Guests")
                        .HasFilter("[E_Mail] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasName("IX_Guests_1");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("GrandLux.Models.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Reservation_Status");
                });

            modelBuilder.Entity("GrandLux.Models.Reservations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnName("Check_In")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnName("Check_Out")
                        .HasColumnType("datetime");

                    b.Property<int?>("Children")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnName("Guest_Id")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationStatus")
                        .HasColumnName("Reservation_Status")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnName("Room_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("ReservationStatus");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GrandLux.Models.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Room_Status");
                });

            modelBuilder.Entity("GrandLux.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxCapacity")
                        .HasColumnName("Max_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NoOfBeds")
                        .HasColumnName("No_of_Beds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Room_Type");
                });

            modelBuilder.Entity("GrandLux.Models.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnName("Check_In")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnName("Check_Out")
                        .HasColumnType("datetime");

                    b.Property<int>("FloorNumber")
                        .HasColumnName("Floor_Number")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnName("Room_Number")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnName("Status_Id")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnName("Type_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique()
                        .HasName("IX_Rooms");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("GrandLux.Models.Reservations", b =>
                {
                    b.HasOne("GrandLux.Models.Guests", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .HasConstraintName("FK_Reservations_Guests")
                        .IsRequired();

                    b.HasOne("GrandLux.Models.ReservationStatus", "ReservationStatusNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatus")
                        .HasConstraintName("FK_Reservations_Reservation_Status");

                    b.HasOne("GrandLux.Models.Rooms", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Reservations_Rooms")
                        .IsRequired();
                });

            modelBuilder.Entity("GrandLux.Models.Rooms", b =>
                {
                    b.HasOne("GrandLux.Models.RoomStatus", "Status")
                        .WithMany("Rooms")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Rooms_Room_Status")
                        .IsRequired();

                    b.HasOne("GrandLux.Models.RoomType", "Type")
                        .WithMany("Rooms")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Rooms_Room_Type")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
